Sprint 11_v0
SergeyMishakov/java-filmorate pull request #3
Opened 2023-02-08 00:13 UTC by SergeyMishakov

2023-02-08 22:13 UTC, db-exp requested changes

2023-02-08 22:13 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      private int id;
"можно лучше" - обычно целочисленные идентификаторы делают с типом long

2023-02-08 22:13 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +public class Genre {
Можно использовать @Data или @Getter/@Setter и не писать кучу геттеров/сеттеров

2023-02-08 22:13 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +public class Mpa {
Можно не писать кучу геттеров/сеттеров

2023-02-08 22:13 UTC, db-exp commented on src/main/resources/schema.sql
> +/*ALTER TABLE films ADD CONSTRAINT IF NOT EXISTS fk_Film_MPA_id FOREIGN KEY(MPA_id)
давай удалим лишнее

2023-02-08 22:13 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        List<Object> userArrayList = jdbcTemplate.query(sql, (rs, rowNum) -> makeUser(rs));
Лучше сразу получать конкретный тип, а не Object
Пример https://medium.com/beingcoders/java-concepts-jdbctemplate-querying-spring-3192bed61f44

2023-02-08 22:13 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    static User makeUser(ResultSet rs) throws SQLException {
не хватает private

2023-02-08 22:13 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        List<Object> userArrayList = jdbcTemplate.query(sql, (rs, rowNum) -> makeUser(rs), firstId, secondId);
лучше возвращать тип

2023-02-08 22:13 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        List<Object> userArrayList = jdbcTemplate.query(sql, (rs, rowNum) -> makeUser(rs), id);
лучше возвращать тип

2023-02-08 22:13 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        List<Object> likeArrayList = jdbcTemplate.query(sql, (rs, rowNum) -> makeLike(rs), filmId);
лучше возвращать тип , пример https://medium.com/beingcoders/java-concepts-jdbctemplate-querying-spring-3192bed61f44

2023-02-08 22:13 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        List<Object> mpaArrayList = jdbcTemplate.query(sql, (rs, rowNum) -> makeMpa(rs));
лучше возвращать тип , пример https://medium.com/beingcoders/java-concepts-jdbctemplate-querying-spring-3192bed61f44

2023-02-08 22:13 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        List<Object> genreArrayList = jdbcTemplate.query(sql, (rs, rowNum) -> makeGenre(rs));
лучше возвращать тип , пример https://medium.com/beingcoders/java-concepts-jdbctemplate-querying-spring-3192bed61f44

2023-02-08 22:13 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        List<Object> genreArrayList = jdbcTemplate.query(sql, (rs, rowNum) -> makeGenre(rs), film.getId());
лучше возвращать тип , пример https://medium.com/beingcoders/java-concepts-jdbctemplate-querying-spring-3192bed61f44

2023-02-08 22:13 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    /*SELECT gof.genre_id,
давай уберем лишнее

2023-02-08 22:13 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        List<Object> filmArrayList = jdbcTemplate.query(sql, (rs, rowNum) -> makeFilm(rs));
лучше возвращать тип , пример https://medium.com/beingcoders/java-concepts-jdbctemplate-querying-spring-3192bed61f44

2023-02-08 22:13 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    static Genre makeGenre(ResultSet rs) throws SQLException {
не хватает private

2023-02-08 22:13 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    static Mpa makeMpa(ResultSet rs) throws SQLException {
не хватает private

2023-02-08 22:13 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    static int makeLike(ResultSet rs) throws SQLException {
не хватает private

2023-02-08 22:13 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    static Film makeFilm(ResultSet rs) throws SQLException {
не хватает private

2023-02-09 05:21 UTC, SergeyMishakov commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +public class Genre {
Выполнено

2023-02-09 05:24 UTC, SergeyMishakov commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +public class Mpa {
Выполнено

2023-02-09 05:25 UTC, SergeyMishakov commented on src/main/resources/schema.sql
> +/*ALTER TABLE films ADD CONSTRAINT IF NOT EXISTS fk_Film_MPA_id FOREIGN KEY(MPA_id)
Выполнено

2023-02-09 05:29 UTC, SergeyMishakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    static Film makeFilm(ResultSet rs) throws SQLException {
Выполнено

2023-02-09 05:30 UTC, SergeyMishakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    static int makeLike(ResultSet rs) throws SQLException {
Выполнено

2023-02-09 05:30 UTC, SergeyMishakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    static Mpa makeMpa(ResultSet rs) throws SQLException {
Выполнено

2023-02-09 05:30 UTC, SergeyMishakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    static Genre makeGenre(ResultSet rs) throws SQLException {
Выполнено

2023-02-09 05:31 UTC, SergeyMishakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    static User makeUser(ResultSet rs) throws SQLException {
Выполнено

2023-02-09 06:25 UTC, SergeyMishakov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      private int id;
Выполнено

2023-02-09 07:09 UTC, SergeyMishakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        List<Object> userArrayList = jdbcTemplate.query(sql, (rs, rowNum) -> makeUser(rs));
Выполнено

2023-02-09 07:10 UTC, SergeyMishakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        List<Object> userArrayList = jdbcTemplate.query(sql, (rs, rowNum) -> makeUser(rs), firstId, secondId);
Выполнено

2023-02-09 07:10 UTC, SergeyMishakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        List<Object> userArrayList = jdbcTemplate.query(sql, (rs, rowNum) -> makeUser(rs), id);
Выполнено

2023-02-09 07:10 UTC, SergeyMishakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        List<Object> likeArrayList = jdbcTemplate.query(sql, (rs, rowNum) -> makeLike(rs), filmId);
Выполнено

2023-02-09 07:10 UTC, SergeyMishakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        List<Object> mpaArrayList = jdbcTemplate.query(sql, (rs, rowNum) -> makeMpa(rs));
Выполнено

2023-02-09 07:11 UTC, SergeyMishakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        List<Object> genreArrayList = jdbcTemplate.query(sql, (rs, rowNum) -> makeGenre(rs));
Выполнено

2023-02-09 07:11 UTC, SergeyMishakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        List<Object> genreArrayList = jdbcTemplate.query(sql, (rs, rowNum) -> makeGenre(rs), film.getId());
Выполнено

2023-02-09 07:11 UTC, SergeyMishakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        List<Object> filmArrayList = jdbcTemplate.query(sql, (rs, rowNum) -> makeFilm(rs));
Выполнено

2023-02-09 07:29 UTC, SergeyMishakov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    /*SELECT gof.genre_id,
Выполнено

2023-02-10 00:12 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                , film.getName()
запятые обычно ставят в конце строки

2023-02-10 00:12 UTC, db-exp approved these changes

2023-02-10 05:17 UTC, merged